export const ROUTES = {
  AUTH_FLOW: 'AuthFlow',
  APP_FLOW: 'AppFlow',
  APP_DRAWER: 'AppDrawer',
  APP_STACK: 'AppStack',
  SPLASH: 'Splash',
  LOGIN: 'Login',
  REGISTER: 'Register',
  FORGOT_PASSWORD: 'ForgotPassword',
  RESET_PASSWORD: 'ResetPassword',
  MAIN_TABS: 'MainTabs',
  DASHBOARD: 'Dashboard',
  REPORTS: 'Reports',
  ADD_TRANSACTION: 'AddTransaction',
  MY_PEOPLE: 'MyPeople',
  PROFILE: 'Profile',
  MY_DETAILS: 'MyDetails',
  EDIT_PROFILE: 'EditProfile',
  CHANGE_PASSWORD: 'ChangePassword',
  PRIVACY_POLICY: 'PrivacyPolicy',
  TERMS_AND_CONDITIONS: 'TermsAndConditions',
  DISCLAIMER: 'Disclaimer',
  DEVELOPER: 'Developer',
  NOTIFICATIONS: 'Notifications',
  TRANSACTION_HISTORY: 'TransactionHistory',
  CONTACT_DETAIL: 'ContactDetail',
  RECORD_REPAYMENT: 'RecordRepayment',
};
