export const ROUTES = {
  AUTH_FLOW: 'AuthFlow',
  APP_FLOW: 'AppFlow',
  SPLASH: 'Splash',
  LOGIN: 'Login',
  REGISTER: 'Register',
  FORGOT_PASSWORD: 'ForgotPassword',
  RESET_PASSWORD: 'ResetPassword',
  MAIN_TABS: 'MainTabs',
  DASHBOARD: 'Dashboard',
  REPORTS: 'Reports',
  ADD_TRANSACTION: 'AddTransaction',
  MY_PEOPLE: 'MyPeople',
  PROFILE: 'Profile',
  MY_DETAILS: 'MyDetails',
  EDIT_PROFILE: 'EditProfile',
  CHANGE_PASSWORD: 'ChangePassword',
  TRANSACTION_HISTORY: 'TransactionHistory',
  CONTACT_DETAIL: 'ContactDetail',
};
